#!/bin/bash
# اسکریپت حل سریع مشکل DNS برای YouTube Downloader
# Quick DNS Fix Script for YouTube Downloader

echo "🔧 شروع حل سریع مشکل DNS..."
echo "🔧 Starting quick DNS fix..."

# رنگ‌ها برای خروجی
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# تابع چاپ رنگی
print_status() {
    case $2 in
        "success") echo -e "${GREEN}✅ $1${NC}" ;;
        "warning") echo -e "${YELLOW}⚠️ $1${NC}" ;;
        "error") echo -e "${RED}❌ $1${NC}" ;;
        *) echo "ℹ️ $1" ;;
    esac
}

# بررسی دسترسی root
if [[ $EUID -ne 0 ]]; then
    print_status "این اسکریپت نیاز به دسترسی sudo دارد" "warning"
    echo "لطفا با sudo اجرا کنید: sudo $0"
    exit 1
fi

# بک‌آپ فایل resolv.conf
print_status "ایجاد بک‌آپ از /etc/resolv.conf..." "info"
if cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S); then
    print_status "بک‌آپ ایجاد شد" "success"
else
    print_status "خطا در ایجاد بک‌آپ" "error"
fi

# تنظیم DNS جدید
print_status "تنظیم DNS servers..." "info"
cat > /etc/resolv.conf << 'EOF'
# YouTube Downloader DNS Configuration
# Generated by quick_dns_fix.sh

# Google Public DNS (Primary)
nameserver 8.8.8.8
nameserver 8.8.4.4

# Cloudflare DNS (Secondary)
nameserver 1.1.1.1
nameserver 1.0.0.1

# DNS Options for better resolution
options timeout:5
options attempts:3
options rotate
options single-request-reopen
options inet6
EOF

if [[ $? -eq 0 ]]; then
    print_status "DNS servers تنظیم شدند" "success"
else
    print_status "خطا در تنظیم DNS" "error"
    exit 1
fi

# راه‌اندازی مجدد سرویس DNS
print_status "راه‌اندازی مجدد سرویس‌های DNS..." "info"

# systemd-resolved
if systemctl is-active --quiet systemd-resolved; then
    systemctl restart systemd-resolved
    print_status "systemd-resolved راه‌اندازی شد" "success"
fi

# networking service
if systemctl is-active --quiet networking; then
    systemctl restart networking
    print_status "networking service راه‌اندازی شد" "success"
fi

# پاک کردن کش DNS
print_status "پاک کردن کش DNS..." "info"
if command -v systemd-resolve &> /dev/null; then
    systemd-resolve --flush-caches
    print_status "کش DNS پاک شد" "success"
fi

# تنظیم پارامترهای شبکه
print_status "تنظیم پارامترهای شبکه..." "info"

# TCP keepalive settings
sysctl -w net.ipv4.tcp_keepalive_time=600 > /dev/null 2>&1
sysctl -w net.ipv4.tcp_keepalive_intvl=60 > /dev/null 2>&1
sysctl -w net.ipv4.tcp_keepalive_probes=3 > /dev/null 2>&1

# Buffer sizes
sysctl -w net.core.rmem_default=262144 > /dev/null 2>&1
sysctl -w net.core.rmem_max=16777216 > /dev/null 2>&1
sysctl -w net.core.wmem_default=262144 > /dev/null 2>&1
sysctl -w net.core.wmem_max=16777216 > /dev/null 2>&1

print_status "پارامترهای شبکه تنظیم شدند" "success"

# تست DNS
print_status "تست DNS..." "info"
sleep 2

# تست با nslookup
if command -v nslookup &> /dev/null; then
    if nslookup youtube.com 8.8.8.8 > /dev/null 2>&1; then
        print_status "تست DNS با Google موفق" "success"
    else
        print_status "تست DNS با Google ناموفق" "warning"
    fi
fi

# تست با dig
if command -v dig &> /dev/null; then
    if dig @1.1.1.1 youtube.com > /dev/null 2>&1; then
        print_status "تست DNS با Cloudflare موفق" "success"
    else
        print_status "تست DNS با Cloudflare ناموفق" "warning"
    fi
fi

# تست ping
print_status "تست اتصال..." "info"
if ping -c 2 youtube.com > /dev/null 2>&1; then
    print_status "اتصال به YouTube موفق" "success"
else
    print_status "اتصال به YouTube ناموفق" "warning"
fi

# ایجاد متغیرهای محیط
print_status "تنظیم متغیرهای محیط..." "info"
cat > /tmp/youtube_env_fix.sh << 'EOF'
#!/bin/bash
# YouTube Downloader Environment Variables

# DNS and Network Settings
export RES_OPTIONS="timeout:5 attempts:3 rotate single-request-reopen"
export SOCKET_TIMEOUT=60
export CONNECT_TIMEOUT=45
export READ_TIMEOUT=120

# Python Settings
export PYTHONUNBUFFERED=1
export PYTHONDONTWRITEBYTECODE=1
export PYTHONHTTPSVERIFY=0

# SSL Settings (if needed)
export CURL_CA_BUNDLE=""
export REQUESTS_CA_BUNDLE=""

echo "🌐 YouTube Downloader environment configured!"
EOF

chmod +x /tmp/youtube_env_fix.sh
print_status "متغیرهای محیط آماده شدند" "success"

# خلاصه نتایج
echo ""
echo "🎉 حل سریع مشکل DNS کامل شد!"
echo "📋 خلاصه تغییرات:"
echo "   • DNS servers: Google (8.8.8.8, 8.8.4.4) + Cloudflare (1.1.1.1, 1.0.0.1)"
echo "   • پارامترهای شبکه بهینه شدند"
echo "   • کش DNS پاک شد"
echo "   • سرویس‌های شبکه راه‌اندازی شدند"
echo ""
echo "📝 مراحل بعدی:"
echo "   1. source /tmp/youtube_env_fix.sh"
echo "   2. python3 test_linux_server.py"
echo "   3. python3 main.py"
echo ""
echo "🔄 در صورت مشکل، برای بازگردانی:"
echo "   sudo cp /etc/resolv.conf.backup.* /etc/resolv.conf"
echo ""

# تست نهایی
print_status "انجام تست نهایی..." "info"
if curl -s -I https://www.youtube.com | grep -q "200 OK"; then
    print_status "✨ همه چیز آماده است! YouTube در دسترس است" "success"
    exit 0
else
    print_status "⚠️ ممکن است نیاز به تنظیمات اضافی باشد" "warning"
    echo "💡 راهنمای کامل را در README_LINUX_SERVER.md مطالعه کنید"
    exit 1
fi