import os
import json
import tempfile

import time
from typing import List, Dict, Optional, Tuple

from yt_dlp import YoutubeDL  # type: ignore

try:
    # Prefer unified DB wrapper
    from .db_wrapper import DB
except Exception:
    from .sqlite_db_wrapper import DB  # fallback


DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')
COOKIES_TMP_DIR = os.path.join(DATA_DIR, 'cookies_tmp')

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(COOKIES_TMP_DIR, exist_ok=True)


def _now_iso() -> str:
    return time.strftime('%Y-%m-%d %H:%M:%S')


def parse_netscape(text: str) -> List[Dict]:
    cookies: List[Dict] = []
    for line in (text or '').splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) != 7:
            # attempt space-separated fallback
            parts = line.split()
        if len(parts) != 7:
            # invalid line, skip
            continue
        domain, flag, path, secure, expiration, name, value = parts
        cookies.append({
            'domain': domain,
            'flag': flag,
            'path': path,
            'secure': secure,
            'expiration': expiration,
            'name': name,
            'value': value,
        })
    return cookies


def parse_json(text: str) -> List[Dict]:
    try:
        data = json.loads(text or '{}')
    except Exception:
        return []
    items: List[Dict] = []
    # Support either dict with 'cookies' or raw list
    if isinstance(data, dict) and 'cookies' in data and isinstance(data['cookies'], list):
        raw = data['cookies']
    elif isinstance(data, list):
        raw = data
    else:
        raw = []
    for c in raw:
        try:
            items.append({
                'domain': c.get('domain', '.youtube.com'),
                'flag': 'TRUE' if not str(c.get('hostOnly', False)).lower() == 'true' else 'FALSE',
                'path': c.get('path', '/'),
                'secure': 'TRUE' if c.get('secure', True) else 'FALSE',
                'expiration': str(c.get('expirationDate', c.get('expires', 0) or 0)).split('.')[0],
                'name': c.get('name', ''),
                'value': c.get('value', ''),
            })
        except Exception:
            continue
    return items


def parse_txt(text: str) -> List[Dict]:
    # Try netscape first
    items = parse_netscape(text)
    if items:
        return items
    # Fallback: simple name=value per line
    cookies: List[Dict] = []
    for line in (text or '').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        name, value = line.split('=', 1)
        cookies.append({
            'domain': '.youtube.com',
            'flag': 'TRUE',
            'path': '/',
            'secure': 'TRUE',
            'expiration': '0',
            'name': name.strip(),
            'value': value.strip(),
        })
    return cookies


def to_netscape(cookies: List[Dict]) -> str:
    lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by DownloaderYT-V1 cookie_manager',
    ]
    for c in cookies:
        try:
            domain = c['domain']
            flag = c.get('flag', 'TRUE')
            path = c.get('path', '/')
            secure = c.get('secure', 'TRUE')
            expiration = str(c.get('expiration', '0'))
            name = c['name']
            value = c['value']
            lines.append('\t'.join([domain, flag, path, secure, expiration, name, value]))
        except KeyError:
            continue
    return '\n'.join(lines) + '\n'


def import_cookie_text(name: str, text: str, source_type: str = 'auto') -> Tuple[bool, str]:
    """Import cookie text in any of supported formats and store as Netscape in DB."""
    cookies: List[Dict] = []
    # Detect format
    if source_type == 'netscape' or '# Netscape HTTP Cookie File' in (text or ''):
        cookies = parse_netscape(text)
        source_type = 'netscape'
    elif source_type == 'json' or (text or '').strip().startswith('{') or (text or '').strip().startswith('['):
        cookies = parse_json(text)
        source_type = 'json'
    else:
        cookies = parse_txt(text)
        source_type = 'txt'
    if not cookies:
        return False, 'کوکی‌ها قابل‌پارس نیستند یا خالی هستند'
    netscape_text = to_netscape(cookies)
    db = DB()
    try:
        if hasattr(db, 'add_cookie'):
            db.add_cookie(name=name, source_type=source_type, cookie_text=netscape_text, fmt='netscape', status='unknown')
        else:
            # Fallback: store to file when DB methods not available
            fallback_path = os.path.join(DATA_DIR, f'cookie_{int(time.time())}.txt')
            with open(fallback_path, 'w', encoding='utf-8') as f:
                f.write(netscape_text)
        return True, 'کوکی با موفقیت ذخیره شد'
    except Exception as e:
        return False, f'خطا در ذخیره کوکی: {e}'


def _write_temp_cookie_file(netscape_text: str) -> str:
    fd, path = tempfile.mkstemp(prefix='yt_cookie_', suffix='.txt', dir=COOKIES_TMP_DIR, text=True)
    with os.fdopen(fd, 'w', encoding='utf-8') as f:
        f.write(netscape_text)
    return path


def validate_cookie(netscape_text: str, timeout: int = 10) -> bool:
    """Validate cookie by simulating yt-dlp extraction with cookiefile.
    
    Tests multiple videos to ensure reliability:
    1. YouTube Shorts (usually more reliable)
    2. Popular video
    3. Fallback video
    """
    # لیست ویدیوهای تست - از محبوب به کم‌تر محبوب
    test_videos = [
        'https://www.youtube.com/watch?v=jNQXAC9IVRw',  # "Me at the zoo" - اولین ویدیوی یوتیوب
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',  # Rick Astley - Never Gonna Give You Up
        'https://www.youtube.com/watch?v=9bZkp7q19f0',  # PSY - Gangnam Style
    ]
    
    path = None
    try:
        path = _write_temp_cookie_file(netscape_text)
        opts = {
            'quiet': True,
            'simulate': True,
            'cookiefile': path,
            'extractor_retries': 0,
            'socket_timeout': timeout,
            'connect_timeout': timeout,
            'no_warnings': True,
            'no_check_certificate': True,
        }
        
        # امتحان هر ویدیو تا یکی موفق شود
        for video_url in test_videos:
            try:
                with YoutubeDL(opts) as ydl:
                    info = ydl.extract_info(video_url, download=False)
                    if info and info.get('id'):
                        # موفق شد - کوکی معتبر است
                        return True
            except Exception:
                # این ویدیو کار نکرد، بعدی را امتحان کن
                continue
        
        # هیچ ویدیویی کار نکرد
        return False
        
    except Exception:
        return False
    finally:
        # پاکسازی فایل موقت
        if path:
            try:
                os.unlink(path)
            except Exception:
                pass


def get_rotated_cookie_file(prev_cookie_id: Optional[int] = None) -> Tuple[Optional[str], Optional[int]]:
    """Pick next cookie (not same as prev) and write a temp netscape file, returning (path, id)."""
    db = DB()
    try:
        if hasattr(db, 'get_next_cookie'):
            rec = db.get_next_cookie(prev_cookie_id)
        else:
            rec = None
        if not rec:
            return None, None
        text = rec.get('cookie_text', '')
        path = _write_temp_cookie_file(text)
        return path, rec.get('id')
    except Exception:
        return None, None


def mark_cookie_used(cookie_id: int, success: bool) -> None:
    db = DB()
    if hasattr(db, 'mark_cookie_used'):
        try:
            db.mark_cookie_used(cookie_id, success)
        except Exception:
            pass


def _sanity_check_youtube_cookie(netscape_text: str) -> bool:
    """Basic structural check: ensure key YouTube auth cookies exist.
    Returns True if at least two critical cookies for .youtube.com are present.
    """
    try:
        critical_names = {
            'SAPISID', 'APISID', 'HSID', 'SSID', 'SID', '__Secure-3PSID', '__Secure-3PAPISID', 'CONSENT'
        }
        count = 0
        for line in (netscape_text or '').splitlines():
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) != 7:
                parts = line.split()
            if len(parts) != 7:
                continue
            domain, flag, path, secure, expiration, name, value = parts
            if '.youtube.com' in domain and name in critical_names and value:
                count += 1
            if count >= 2:
                return True
        return False
    except Exception:
        return False


def validate_and_update_cookie_status(cookie_id: int) -> bool:
    """اعتبارسنجی کوکی و به‌روزرسانی وضعیت آن.
    
    سطح اول: بررسی ساختاری (سریع)
    سطح دوم: تست واقعی با yt-dlp (کامل ولی کندتر)
    
    اگر یوتیوب captcha بخواهد، بررسی ساختاری کافی است.
    """
    db = DB()
    try:
        recs = db.get_cookie_by_id(cookie_id) if hasattr(db, 'get_cookie_by_id') else []
        rec = recs[0] if isinstance(recs, list) and recs else recs
        if not rec:
            return False
        text = rec.get('cookie_text', '')
        
        # سطح اول: بررسی ساختاری (همیشه انجام می‌شود)
        ok_sanity = _sanity_check_youtube_cookie(text)
        
        # سطح دوم: تست واقعی با yt-dlp (فقط اگر ساختار صحیح بود)
        ok_extract = False
        if ok_sanity:
            try:
                ok_extract = validate_cookie(text, timeout=15)
            except Exception:
                # اگر خطا داد (مثلاً captcha)، بررسی ساختاری کافی است
                ok_extract = False
        
        # اگر یکی از دو موفق بود، کوکی معتبر است
        # اولویت با تست واقعی، ولی اگر captcha بود ساختار کافی است
        final_ok = bool(ok_extract or ok_sanity)
        
        # تعیین وضعیت دقیق‌تر
        if ok_extract:
            status = 'valid'  # کوکی کاملاً معتبر - تست شد
        elif ok_sanity:
            status = 'valid'  # کوکی معتبر - ساختار صحیح است
        else:
            status = 'invalid'  # کوکی نامعتبر
        
        if hasattr(db, 'update_cookie_status'):
            db.update_cookie_status(cookie_id, status)
        
        return final_ok
    except Exception:
        return False


def get_main_cookie_file() -> Optional[str]:
    """
    خواندن کوکی از فایل اصلی cookie_youtube.txt و ایجاد فایل موقت
    """
    try:
        # مسیر فایل کوکی اصلی
        main_cookie_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'cookie_youtube.txt')
        
        if not os.path.exists(main_cookie_path):
            return None
            
        # خواندن محتوای فایل
        with open(main_cookie_path, 'r', encoding='utf-8') as f:
            cookie_content = f.read().strip()
            
        if not cookie_content:
            return None
            
        # بررسی اعتبار کوکی
        if not _sanity_check_youtube_cookie(cookie_content):
            return None
            
        # ایجاد فایل موقت
        temp_file_path = _write_temp_cookie_file(cookie_content)
        return temp_file_path
        
    except Exception as e:
        print(f"خطا در خواندن فایل کوکی اصلی: {e}")
        return None


def get_cookie_file_with_fallback(prev_cookie_id: Optional[int] = None) -> Tuple[Optional[str], Optional[int]]:
    """
    ابتدا سعی می‌کند کوکی از فایل اصلی بخواند، در صورت عدم موفقیت از استخر کوکی استفاده می‌کند
    """
    # ابتدا تلاش برای استفاده از فایل اصلی
    main_cookie_path = get_main_cookie_file()
    if main_cookie_path:
        return main_cookie_path, -1  # -1 نشان‌دهنده کوکی اصلی است
    
    # در صورت عدم موفقیت، از استخر کوکی استفاده کن
    return get_rotated_cookie_file(prev_cookie_id)